# Generated by Django 5.1.1 on 2024-09-07 10:43

import autoslug.fields
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('name',))),
                ('tax_number', models.CharField(blank=True, max_length=255)),
                ('registration_no', models.CharField(blank=True, max_length=50)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('website_url', models.URLField(blank=True)),
                ('blog_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('whatsapp_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('summary', models.CharField(blank=True, help_text='Short summary about restaurant.', max_length=1000)),
                ('description', models.CharField(blank=True, help_text='Longer description about restaurant.', max_length=1000)),
                ('store_front_photo', models.ImageField(blank=True, height_field='height', null=True, upload_to='', width_field='width')),
                ('cover_photo', models.ImageField(blank=True, height_field='height', null=True, upload_to='', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLACEHOLDER', 'Placeholder'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('short_pitch', models.CharField(blank=True, max_length=500)),
                ('services', models.CharField(blank=True, help_text='Services that the company provides', max_length=800)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('HR', 'Human Resource'), ('CHEF', 'Chef'), ('STAFF', 'Staff'), ('WAITER', 'Waiter'), ('SECURITY', 'Security')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'PENDING'), ('SUSPENDED', 'Suspended'), ('Fired', 'Fired')], default='ACTIVE', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
