# Generated by Django 5.1.1 on 2024-09-07 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_organizationmember'),
        ('mediaroom', '0002_mediaroomconnector'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='media_files',
            field=models.ManyToManyField(blank=True, through='mediaroom.MediaRoomConnector', to='mediaroom.mediaroom'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'member')},
        ),
    ]
