# Generated by Django 5.1.1 on 2024-09-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressio', '0003_addressconnector_organization'),
        ('core', '0003_organization_media_files_organizationmember_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='addresses',
            field=models.ManyToManyField(blank=True, through='addressio.AddressConnector', to='addressio.address'),
        ),
    ]
