# Generated by Django 5.1.1 on 2024-09-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('CHEF', 'Chef'), ('STAFF', 'Staff'), ('WAITER', 'Waiter'), ('SECURITY', 'Security')], max_length=20),
        ),
    ]
