# Generated by Django 5.1.1 on 2024-09-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmember',
            name='slug',
        ),
    ]
