# Generated by Django 5.1.1 on 2024-09-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_organizationmember_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='cover_photo',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='images/covers/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='store_front_photo',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='images/store_fronts/', width_field='width'),
        ),
    ]
