# Generated by Django 5.1.1 on 2024-09-08 13:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaroom', '0002_mediaroomconnector'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaroom',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique_with=('name',)),
        ),
        migrations.AddField(
            model_name='mediaroomconnector',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique_with=('name',)),
        ),
    ]
