# Generated by Django 5.1.1 on 2024-09-08 13:59

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressio', '0003_addressconnector_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique_with=('name',)),
        ),
        migrations.AddField(
            model_name='addressconnector',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='addressconnector',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique_with=('name',)),
        ),
        migrations.AddField(
            model_name='district',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique_with=('name',)),
        ),
        migrations.AddField(
            model_name='division',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique_with=('name',)),
        ),
        migrations.AddField(
            model_name='postoffice',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique_with=('name',)),
        ),
        migrations.AddField(
            model_name='upazila',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique_with=('name',)),
        ),
    ]
