# Generated by Django 5.1.1 on 2024-09-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressio', '0004_address_name_address_slug_addressconnector_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='addressconnector',
            name='name',
        ),
        migrations.RemoveField(
            model_name='addressconnector',
            name='slug',
        ),
    ]
