# Generated by Django 5.1.1 on 2024-09-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='slug',
        ),
    ]
