# Generated by Django 5.1.1 on 2024-09-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='tag_line',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('IN PROGRESS', 'In Progress'), ('DRAFT', 'Draft')], default='DRAFT'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('IN PROGRESS', 'In Progress'), ('DRAFT', 'Draft')], default='DRAFT'),
        ),
    ]
