# Generated by Django 5.1.1 on 2024-09-08 13:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_tag_line_alter_menu_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique_with=('name',)),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique_with=('name',)),
        ),
    ]
